export const RESET_MESSAGE = 'RESET_MESSAGE';

export const LOGIN_PROGRESS = "LOGIN_PROGRESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_PROGRESS = "LOGOUT_PROGRESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
// ====================user ======================
export const GET_USER_LIST_PROGRESS = "GET_USER_LIST_PROGRESS";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAILURE = "GET_USER_LIST_FAILURE";

export const ADD_USER_PROGRESS = "ADD_USER_PROGRESS";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const EDIT_DELETE_USER_PROGRESS = "EDIT_DELETE_USER_PROGRESS";
export const EDIT_DELETE_USER_SUCCESS = "EDIT_DELETE_USER_SUCCESS";
export const EDIT_DELETE_USER_FAILURE = "EDIT_DELETE_USER_FAILURE";

// ====================body type ======================
export const GET_BODY_TYPE_LIST_PROGRESS = "GET_BODY_TYPE_LIST_PROGRESS";
export const GET_BODY_TYPE_LIST_SUCCESS = "GET_BODY_TYPE_LIST_SUCCESS";
export const GET_BODY_TYPE_LIST_FAILURE = "GET_BODY_TYPE_LIST_FAILURE";

export const ADD_BODY_TYPE_PROGRESS = "ADD_BODY_TYPE_PROGRESS";
export const ADD_BODY_TYPE_SUCCESS = "ADD_BODY_TYPE_SUCCESS";
export const ADD_BODY_TYPE_FAILURE = "ADD_BODY_TYPE_FAILURE";

export const EDIT_DELETE_BODY_TYPE_PROGRESS = "EDIT_DELETE_BODY_TYPE_PROGRESS";
export const EDIT_DELETE_BODY_TYPE_SUCCESS = "EDIT_DELETE_BODY_TYPE_SUCCESS";
export const EDIT_DELETE_BODY_TYPE_FAILURE = "EDIT_DELETE_BODY_TYPE_FAILURE";

export const UPLOAD_BODY_TYPE_IMAGE_PROGRESS = "UPLOAD_BODY_TYPE_IMAGE_PROGRESS";
export const UPLOAD_BODY_TYPE_IMAGE_SUCCESS = "UPLOAD_BODY_TYPE_IMAGE_SUCCESS";
export const UPLOAD_BODY_TYPE_IMAGE_FAILURE = "UPLOAD_BODY_TYPE_IMAGE_FAILURE";

// ====================brand ======================
export const GET_BRAND_LIST_PROGRESS = "GET_BRAND_LIST_PROGRESS";
export const GET_BRAND_LIST_SUCCESS = "GET_BRAND_LIST_SUCCESS";
export const GET_BRAND_LIST_FAILURE = "GET_BRAND_LIST_FAILURE";

export const ADD_BRAND_PROGRESS = "ADD_BRAND_PROGRESS";
export const ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS";
export const ADD_BRAND_FAILURE = "ADD_BRAND_FAILURE";

export const EDIT_DELETE_BRAND_PROGRESS = "EDIT_DELETE_BRAND_PROGRESS";
export const EDIT_DELETE_BRAND_SUCCESS = "EDIT_DELETE_BRAND_SUCCESS";
export const EDIT_DELETE_BRAND_FAILURE = "EDIT_DELETE_BRAND_FAILURE";

// ====================charges ======================
export const GET_CHARGES_LIST_PROGRESS = "GET_CHARGES_LIST_PROGRESS";
export const GET_CHARGES_LIST_SUCCESS = "GET_CHARGES_LIST_SUCCESS";
export const GET_CHARGES_LIST_FAILURE = "GET_CHARGES_LIST_FAILURE";

export const ADD_CHARGES_PROGRESS = "ADD_CHARGES_PROGRESS";
export const ADD_CHARGES_SUCCESS = "ADD_CHARGES_SUCCESS";
export const ADD_CHARGES_FAILURE = "ADD_CHARGES_FAILURE";

export const EDIT_DELETE_CHARGES_PROGRESS = "EDIT_DELETE_CHARGES_PROGRESS";
export const EDIT_DELETE_CHARGES_SUCCESS = "EDIT_DELETE_CHARGES_SUCCESS";
export const EDIT_DELETE_CHARGES_FAILURE = "EDIT_DELETE_CHARGES_FAILURE";

// ====================color ======================
export const GET_COLOR_LIST_PROGRESS = "GET_COLOR_LIST_PROGRESS";
export const GET_COLOR_LIST_SUCCESS = "GET_COLOR_LIST_SUCCESS";
export const GET_COLOR_LIST_FAILURE = "GET_COLOR_LIST_FAILURE";

export const ADD_COLOR_PROGRESS = "ADD_COLOR_PROGRESS";
export const ADD_COLOR_SUCCESS = "ADD_COLOR_SUCCESS";
export const ADD_COLOR_FAILURE = "ADD_COLOR_FAILURE";

export const EDIT_DELETE_COLOR_PROGRESS = "EDIT_DELETE_COLOR_PROGRESS";
export const EDIT_DELETE_COLOR_SUCCESS = "EDIT_DELETE_COLOR_SUCCESS";
export const EDIT_DELETE_COLOR_FAILURE = "EDIT_DELETE_COLOR_FAILURE";

// ====================employee ======================
export const GET_EMPLOYEE_LIST_PROGRESS = "GET_EMPLOYEE_LIST_PROGRESS";
export const GET_EMPLOYEE_LIST_SUCCESS = "GET_EMPLOYEE_LIST_SUCCESS";
export const GET_EMPLOYEE_LIST_FAILURE = "GET_EMPLOYEE_LIST_FAILURE";

export const ADD_EMPLOYEE_PROGRESS = "ADD_EMPLOYEE_PROGRESS";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";

export const EDIT_DELETE_EMPLOYEE_PROGRESS = "EDIT_DELETE_EMPLOYEE_PROGRESS";
export const EDIT_DELETE_EMPLOYEE_SUCCESS = "EDIT_DELETE_EMPLOYEE_SUCCESS";
export const EDIT_DELETE_EMPLOYEE_FAILURE = "EDIT_DELETE_EMPLOYEE_FAILURE";

// ====================fabric feel ======================
export const GET_FABRIC_FEEL_LIST_PROGRESS = "GET_FABRIC_FEEL_LIST_PROGRESS";
export const GET_FABRIC_FEEL_LIST_SUCCESS = "GET_FABRIC_FEEL_LIST_SUCCESS";
export const GET_FABRIC_FEEL_LIST_FAILURE = "GET_FABRIC_FEEL_LIST_FAILURE";

export const ADD_FABRIC_FEEL_PROGRESS = "ADD_FABRIC_FEEL_PROGRESS";
export const ADD_FABRIC_FEEL_SUCCESS = "ADD_FABRIC_FEEL_SUCCESS";
export const ADD_FABRIC_FEEL_FAILURE = "ADD_FABRIC_FEEL_FAILURE";

export const EDIT_DELETE_FABRIC_FEEL_PROGRESS = "EDIT_DELETE_FABRIC_FEEL_PROGRESS";
export const EDIT_DELETE_FABRIC_FEEL_SUCCESS = "EDIT_DELETE_FABRIC_FEEL_SUCCESS";
export const EDIT_DELETE_FABRIC_FEEL_FAILURE = "EDIT_DELETE_FABRIC_FEEL_FAILURE";

// ====================fabric material ======================
export const GET_FABRIC_MATERIAL_LIST_PROGRESS = "GET_FABRIC_MATERIAL_LIST_PROGRESS";
export const GET_FABRIC_MATERIAL_LIST_SUCCESS = "GET_FABRIC_MATERIAL_LIST_SUCCESS";
export const GET_FABRIC_MATERIAL_LIST_FAILURE = "GET_FABRIC_MATERIAL_LIST_FAILURE";

export const ADD_FABRIC_MATERIAL_PROGRESS = "ADD_FABRIC_MATERIAL_PROGRESS";
export const ADD_FABRIC_MATERIAL_SUCCESS = "ADD_FABRIC_MATERIAL_SUCCESS";
export const ADD_FABRIC_MATERIAL_FAILURE = "ADD_FABRIC_MATERIAL_FAILURE";

export const EDIT_DELETE_FABRIC_MATERIAL_PROGRESS = "EDIT_DELETE_FABRIC_MATERIAL_PROGRESS";
export const EDIT_DELETE_FABRIC_MATERIAL_SUCCESS = "EDIT_DELETE_FABRIC_MATERIAL_SUCCESS";
export const EDIT_DELETE_FABRIC_MATERIAL_FAILURE = "EDIT_DELETE_FABRIC_MATERIAL_FAILURE";

// ====================fabric quality ======================
export const GET_FABRIC_QUALITY_LIST_PROGRESS = "GET_FABRIC_QUALITY_LIST_PROGRESS";
export const GET_FABRIC_QUALITY_LIST_SUCCESS = "GET_FABRIC_QUALITY_LIST_SUCCESS";
export const GET_FABRIC_QUALITY_LIST_FAILURE = "GET_FABRIC_QUALITY_LIST_FAILURE";

export const ADD_FABRIC_QUALITY_PROGRESS = "ADD_FABRIC_QUALITY_PROGRESS";
export const ADD_FABRIC_QUALITY_SUCCESS = "ADD_FABRIC_QUALITY_SUCCESS";
export const ADD_FABRIC_QUALITY_FAILURE = "ADD_FABRIC_QUALITY_FAILURE";

export const EDIT_DELETE_FABRIC_QUALITY_PROGRESS = "EDIT_DELETE_FABRIC_QUALITY_PROGRESS";
export const EDIT_DELETE_FABRIC_QUALITY_SUCCESS = "EDIT_DELETE_FABRIC_QUALITY_SUCCESS";
export const EDIT_DELETE_FABRIC_QUALITY_FAILURE = "EDIT_DELETE_FABRIC_QUALITY_FAILURE";

// ====================fabric use ======================
export const GET_FABRIC_USE_LIST_PROGRESS = "GET_FABRIC_USE_LIST_PROGRESS";
export const GET_FABRIC_USE_LIST_SUCCESS = "GET_FABRIC_USE_LIST_SUCCESS";
export const GET_FABRIC_USE_LIST_FAILURE = "GET_FABRIC_USE_LIST_FAILURE";

export const ADD_FABRIC_USE_PROGRESS = "ADD_FABRIC_USE_PROGRESS";
export const ADD_FABRIC_USE_SUCCESS = "ADD_FABRIC_USE_SUCCESS";
export const ADD_FABRIC_USE_FAILURE = "ADD_FABRIC_USE_FAILURE";

export const EDIT_DELETE_FABRIC_USE_PROGRESS = "EDIT_DELETE_FABRIC_USE_PROGRESS";
export const EDIT_DELETE_FABRIC_USE_SUCCESS = "EDIT_DELETE_FABRIC_USE_SUCCESS";
export const EDIT_DELETE_FABRIC_USE_FAILURE = "EDIT_DELETE_FABRIC_USE_FAILURE";

// ====================occasion ======================
export const GET_OCCASION_LIST_PROGRESS = "GET_OCCASION_LIST_PROGRESS";
export const GET_OCCASION_LIST_SUCCESS = "GET_OCCASION_LIST_SUCCESS";
export const GET_OCCASION_LIST_FAILURE = "GET_OCCASION_LIST_FAILURE";

export const ADD_OCCASION_PROGRESS = "ADD_OCCASION_PROGRESS";
export const ADD_OCCASION_SUCCESS = "ADD_OCCASION_SUCCESS";
export const ADD_OCCASION_FAILURE = "ADD_OCCASION_FAILURE";

export const EDIT_DELETE_OCCASION_PROGRESS = "EDIT_DELETE_OCCASION_PROGRESS";
export const EDIT_DELETE_OCCASION_SUCCESS = "EDIT_DELETE_OCCASION_SUCCESS";
export const EDIT_DELETE_OCCASION_FAILURE = "EDIT_DELETE_OCCASION_FAILURE";

// ====================pattern ======================
export const GET_PATTERN_LIST_PROGRESS = "GET_PATTERN_LIST_PROGRESS";
export const GET_PATTERN_LIST_SUCCESS = "GET_PATTERN_LIST_SUCCESS";
export const GET_PATTERN_LIST_FAILURE = "GET_PATTERN_LIST_FAILURE";

export const ADD_PATTERN_PROGRESS = "ADD_PATTERN_PROGRESS";
export const ADD_PATTERN_SUCCESS = "ADD_PATTERN_SUCCESS";
export const ADD_PATTERN_FAILURE = "ADD_PATTERN_FAILURE";

export const EDIT_DELETE_PATTERN_PROGRESS = "EDIT_DELETE_PATTERN_PROGRESS";
export const EDIT_DELETE_PATTERN_SUCCESS = "EDIT_DELETE_PATTERN_SUCCESS";
export const EDIT_DELETE_PATTERN_FAILURE = "EDIT_DELETE_PATTERN_FAILURE";

// ====================role ======================
export const GET_ROLE_LIST_PROGRESS = "GET_ROLE_LIST_PROGRESS";
export const GET_ROLE_LIST_SUCCESS = "GET_ROLE_LIST_SUCCESS";
export const GET_ROLE_LIST_FAILURE = "GET_ROLE_LIST_FAILURE";

export const ADD_ROLE_PROGRESS = "ADD_ROLE_PROGRESS";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAILURE = "ADD_ROLE_FAILURE";

export const EDIT_DELETE_ROLE_PROGRESS = "EDIT_DELETE_ROLE_PROGRESS";
export const EDIT_DELETE_ROLE_SUCCESS = "EDIT_DELETE_ROLE_SUCCESS";
export const EDIT_DELETE_ROLE_FAILURE = "EDIT_DELETE_ROLE_FAILURE";

// ====================unit ======================
export const GET_UNIT_LIST_PROGRESS = "GET_UNIT_LIST_PROGRESS";
export const GET_UNIT_LIST_SUCCESS = "GET_UNIT_LIST_SUCCESS";
export const GET_UNIT_LIST_FAILURE = "GET_UNIT_LIST_FAILURE";

export const ADD_UNIT_PROGRESS = "ADD_UNIT_PROGRESS";
export const ADD_UNIT_SUCCESS = "ADD_UNIT_SUCCESS";
export const ADD_UNIT_FAILURE = "ADD_UNIT_FAILURE";

export const EDIT_DELETE_UNIT_PROGRESS = "EDIT_DELETE_UNIT_PROGRESS";
export const EDIT_DELETE_UNIT_SUCCESS = "EDIT_DELETE_UNIT_SUCCESS";
export const EDIT_DELETE_UNIT_FAILURE = "EDIT_DELETE_UNIT_FAILURE";

// ====================Shirt BackPleat ======================
export const GET_SHIRT_BACKPLEAT_LIST_PROGRESS = "GET_SHIRT_BACKPLEAT_LIST_PROGRESS";
export const GET_SHIRT_BACKPLEAT_LIST_SUCCESS = "GET_SHIRT_BACKPLEAT_LIST_SUCCESS";
export const GET_SHIRT_BACKPLEAT_LIST_FAILURE = "GET_SHIRT_BACKPLEAT_LIST_FAILURE";

export const ADD_SHIRT_BACKPLEAT_PROGRESS = "ADD_SHIRT_BACKPLEAT_PROGRESS";
export const ADD_SHIRT_BACKPLEAT_SUCCESS = "ADD_SHIRT_BACKPLEAT_SUCCESS";
export const ADD_SHIRT_BACKPLEAT_FAILURE = "ADD_SHIRT_BACKPLEAT_FAILURE";

export const EDIT_DELETE_SHIRT_BACKPLEAT_PROGRESS = "EDIT_DELETE_SHIRT_BACKPLEAT_PROGRESS";
export const EDIT_DELETE_SHIRT_BACKPLEAT_SUCCESS = "EDIT_DELETE_SHIRT_BACKPLEAT_SUCCESS";
export const EDIT_DELETE_SHIRT_BACKPLEAT_FAILURE = "EDIT_DELETE_SHIRT_BACKPLEAT_FAILURE";

export const UPLOAD_SHIRT_BACKPLEAT_IMAGE_PROGRESS = "UPLOAD_SHIRT_BACKPLEAT_IMAGE_PROGRESS";
export const UPLOAD_SHIRT_BACKPLEAT_IMAGE_SUCCESS = "UPLOAD_SHIRT_BACKPLEAT_IMAGE_SUCCESS";
export const UPLOAD_SHIRT_BACKPLEAT_IMAGE_FAILURE = "UPLOAD_SHIRT_BACKPLEAT_IMAGE_FAILURE";

// ====================shirt bottom ======================
export const GET_SHIRT_BOTTOM_LIST_PROGRESS = "GET_SHIRT_BOTTOM_LIST_PROGRESS";
export const GET_SHIRT_BOTTOM_LIST_SUCCESS = "GET_SHIRT_BOTTOM_LIST_SUCCESS";
export const GET_SHIRT_BOTTOM_LIST_FAILURE = "GET_SHIRT_BOTTOM_LIST_FAILURE";

export const ADD_SHIRT_BOTTOM_PROGRESS = "ADD_SHIRT_BOTTOM_PROGRESS";
export const ADD_SHIRT_BOTTOM_SUCCESS = "ADD_SHIRT_BOTTOM_SUCCESS";
export const ADD_SHIRT_BOTTOM_FAILURE = "ADD_SHIRT_BOTTOM_FAILURE";

export const EDIT_DELETE_SHIRT_BOTTOM_PROGRESS = "EDIT_DELETE_SHIRT_BOTTOM_PROGRESS";
export const EDIT_DELETE_SHIRT_BOTTOM_SUCCESS = "EDIT_DELETE_SHIRT_BOTTOM_SUCCESS";
export const EDIT_DELETE_SHIRT_BOTTOM_FAILURE = "EDIT_DELETE_SHIRT_BOTTOM_FAILURE";

export const UPLOAD_SHIRT_BOTTOM_IMAGE_PROGRESS = "UPLOAD_SHIRT_BOTTOM_IMAGE_PROGRESS";
export const UPLOAD_SHIRT_BOTTOM_IMAGE_SUCCESS = "UPLOAD_SHIRT_BOTTOM_IMAGE_SUCCESS";
export const UPLOAD_SHIRT_BOTTOM_IMAGE_FAILURE = "UPLOAD_SHIRT_BOTTOM_IMAGE_FAILURE";

// ====================shirt collar cuff thickness ======================
export const GET_SHIRT_COLLAR_CUFF_THICKNESS_LIST_PROGRESS = "GET_SHIRT_COLLAR_CUFF_THICKNESS_LIST_PROGRESS";
export const GET_SHIRT_COLLAR_CUFF_THICKNESS_LIST_SUCCESS = "GET_SHIRT_COLLAR_CUFF_THICKNESS_LIST_SUCCESS";
export const GET_SHIRT_COLLAR_CUFF_THICKNESS_LIST_FAILURE = "GET_SHIRT_COLLAR_CUFF_THICKNESS_LIST_FAILURE";

export const ADD_SHIRT_COLLAR_CUFF_THICKNESS_PROGRESS = "ADD_SHIRT_COLLAR_CUFF_THICKNESS_PROGRESS";
export const ADD_SHIRT_COLLAR_CUFF_THICKNESS_SUCCESS = "ADD_SHIRT_COLLAR_CUFF_THICKNESS_SUCCESS";
export const ADD_SHIRT_COLLAR_CUFF_THICKNESS_FAILURE = "ADD_SHIRT_COLLAR_CUFF_THICKNESS_FAILURE";

export const EDIT_DELETE_SHIRT_COLLAR_CUFF_THICKNESS_PROGRESS = "EDIT_DELETE_SHIRT_COLLAR_CUFF_THICKNESS_PROGRESS";
export const EDIT_DELETE_SHIRT_COLLAR_CUFF_THICKNESS_SUCCESS = "EDIT_DELETE_SHIRT_COLLAR_CUFF_THICKNESS_SUCCESS";
export const EDIT_DELETE_SHIRT_COLLAR_CUFF_THICKNESS_FAILURE = "EDIT_DELETE_SHIRT_COLLAR_CUFF_THICKNESS_FAILURE";

export const UPLOAD_SHIRT_COLLAR_CUFF_THICKNESS_IMAGE_PROGRESS = "UPLOAD_SHIRT_COLLAR_CUFF_THICKNESS_IMAGE_PROGRESS";
export const UPLOAD_SHIRT_COLLAR_CUFF_THICKNESS_IMAGE_SUCCESS = "UPLOAD_SHIRT_COLLAR_CUFF_THICKNESS_IMAGE_SUCCESS";
export const UPLOAD_SHIRT_COLLAR_CUFF_THICKNESS_IMAGE_FAILURE = "UPLOAD_SHIRT_COLLAR_CUFF_THICKNESS_IMAGE_FAILURE";

// ====================shirt collar ======================
export const GET_SHIRT_COLLAR_LIST_PROGRESS = "GET_SHIRT_COLLAR_LIST_PROGRESS";
export const GET_SHIRT_COLLAR_LIST_SUCCESS = "GET_SHIRT_COLLAR_LIST_SUCCESS";
export const GET_SHIRT_COLLAR_LIST_FAILURE = "GET_SHIRT_COLLAR_LIST_FAILURE";

export const ADD_SHIRT_COLLAR_PROGRESS = "ADD_SHIRT_COLLAR_PROGRESS";
export const ADD_SHIRT_COLLAR_SUCCESS = "ADD_SHIRT_COLLAR_SUCCESS";
export const ADD_SHIRT_COLLAR_FAILURE = "ADD_SHIRT_COLLAR_FAILURE";

export const EDIT_DELETE_SHIRT_COLLAR_PROGRESS = "EDIT_DELETE_SHIRT_COLLAR_PROGRESS";
export const EDIT_DELETE_SHIRT_COLLAR_SUCCESS = "EDIT_DELETE_SHIRT_COLLAR_SUCCESS";
export const EDIT_DELETE_SHIRT_COLLAR_FAILURE = "EDIT_DELETE_SHIRT_COLLAR_FAILURE";

export const UPLOAD_SHIRT_COLLAR_IMAGE_PROGRESS = "UPLOAD_SHIRT_COLLAR_IMAGE_PROGRESS";
export const UPLOAD_SHIRT_COLLAR_IMAGE_SUCCESS = "UPLOAD_SHIRT_COLLAR_IMAGE_SUCCESS";
export const UPLOAD_SHIRT_COLLAR_IMAGE_FAILURE = "UPLOAD_SHIRT_COLLAR_IMAGE_FAILURE";

// ====================shirt Cuff ======================
export const GET_SHIRT_CUFF_LIST_PROGRESS = "GET_SHIRT_CUFF_LIST_PROGRESS";
export const GET_SHIRT_CUFF_LIST_SUCCESS = "GET_SHIRT_CUFF_LIST_SUCCESS";
export const GET_SHIRT_CUFF_LIST_FAILURE = "GET_SHIRT_CUFF_LIST_FAILURE";

export const ADD_SHIRT_CUFF_PROGRESS = "ADD_SHIRT_CUFF_PROGRESS";
export const ADD_SHIRT_CUFF_SUCCESS = "ADD_SHIRT_CUFF_SUCCESS";
export const ADD_SHIRT_CUFF_FAILURE = "ADD_SHIRT_CUFF_FAILURE";

export const EDIT_DELETE_SHIRT_CUFF_PROGRESS = "EDIT_DELETE_SHIRT_CUFF_PROGRESS";
export const EDIT_DELETE_SHIRT_CUFF_SUCCESS = "EDIT_DELETE_SHIRT_CUFF_SUCCESS";
export const EDIT_DELETE_SHIRT_CUFF_FAILURE = "EDIT_DELETE_SHIRT_CUFF_FAILURE";

// ====================shirt fitting  ======================
export const GET_SHIRT_FITTING_LIST_PROGRESS = "GET_SHIRT_FITTING_LIST_PROGRESS";
export const GET_SHIRT_FITTING_LIST_SUCCESS = "GET_SHIRT_FITTING_LIST_SUCCESS";
export const GET_SHIRT_FITTING_LIST_FAILURE = "GET_SHIRT_FITTING_LIST_FAILURE";

export const ADD_SHIRT_FITTING_PROGRESS = "ADD_SHIRT_FITTING_PROGRESS";
export const ADD_SHIRT_FITTING_SUCCESS = "ADD_SHIRT_FITTING_SUCCESS";
export const ADD_SHIRT_FITTING_FAILURE = "ADD_SHIRT_FITTING_FAILURE";

export const EDIT_DELETE_SHIRT_FITTING_PROGRESS = "EDIT_DELETE_SHIRT_FITTING_PROGRESS";
export const EDIT_DELETE_SHIRT_FITTING_SUCCESS = "EDIT_DELETE_SHIRT_FITTING_SUCCESS";
export const EDIT_DELETE_SHIRT_FITTING_FAILURE = "EDIT_DELETE_SHIRT_FITTING_FAILURE";

// ====================shirt front ======================
export const GET_SHIRT_FRONT_LIST_PROGRESS = "GET_SHIRT_FRONT_LIST_PROGRESS";
export const GET_SHIRT_FRONT_LIST_SUCCESS = "GET_SHIRT_FRONT_LIST_SUCCESS";
export const GET_SHIRT_FRONT_LIST_FAILURE = "GET_SHIRT_FRONT_LIST_FAILURE";

export const ADD_SHIRT_FRONT_PROGRESS = "ADD_SHIRT_FRONT_PROGRESS";
export const ADD_SHIRT_FRONT_SUCCESS = "ADD_SHIRT_FRONT_SUCCESS";
export const ADD_SHIRT_FRONT_FAILURE = "ADD_SHIRT_FRONT_FAILURE";

export const EDIT_DELETE_SHIRT_FRONT_PROGRESS = "EDIT_DELETE_SHIRT_FRONT_PROGRESS";
export const EDIT_DELETE_SHIRT_FRONT_SUCCESS = "EDIT_DELETE_SHIRT_FRONT_SUCCESS";
export const EDIT_DELETE_SHIRT_FRONT_FAILURE = "EDIT_DELETE_SHIRT_FRONT_FAILURE";

export const UPLOAD_SHIRT_FRONT_IMAGE_PROGRESS = "UPLOAD_SHIRT_FRONT_IMAGE_PROGRESS";
export const UPLOAD_SHIRT_FRONT_IMAGE_SUCCESS = "UPLOAD_SHIRT_FRONT_IMAGE_SUCCESS";
export const UPLOAD_SHIRT_FRONT_IMAGE_FAILURE = "UPLOAD_SHIRT_FRONT_IMAGE_FAILURE";

// ====================shirt bottom ======================
export const GET_SHIRT_POCKET_LIST_PROGRESS = "GET_SHIRT_POCKET_LIST_PROGRESS";
export const GET_SHIRT_POCKET_LIST_SUCCESS = "GET_SHIRT_POCKET_LIST_SUCCESS";
export const GET_SHIRT_POCKET_LIST_FAILURE = "GET_SHIRT_POCKET_LIST_FAILURE";

export const ADD_SHIRT_POCKET_PROGRESS = "ADD_SHIRT_POCKET_PROGRESS";
export const ADD_SHIRT_POCKET_SUCCESS = "ADD_SHIRT_POCKET_SUCCESS";
export const ADD_SHIRT_POCKET_FAILURE = "ADD_SHIRT_POCKET_FAILURE";

export const EDIT_DELETE_SHIRT_POCKET_PROGRESS = "EDIT_DELETE_SHIRT_POCKET_PROGRESS";
export const EDIT_DELETE_SHIRT_POCKET_SUCCESS = "EDIT_DELETE_SHIRT_POCKET_SUCCESS";
export const EDIT_DELETE_SHIRT_POCKET_FAILURE = "EDIT_DELETE_SHIRT_POCKET_FAILURE";

export const UPLOAD_SHIRT_POCKET_IMAGE_PROGRESS = "UPLOAD_SHIRT_POCKET_IMAGE_PROGRESS";
export const UPLOAD_SHIRT_POCKET_IMAGE_SUCCESS = "UPLOAD_SHIRT_POCKET_IMAGE_SUCCESS";
export const UPLOAD_SHIRT_POCKET_IMAGE_FAILURE = "UPLOAD_SHIRT_POCKET_IMAGE_FAILURE";

// ====================trouser bottom master ======================
export const GET_TROUSER_BOTTOM_LIST_PROGRESS = "GET_TROUSER_BOTTOM_LIST_PROGRESS";
export const GET_TROUSER_BOTTOM_LIST_SUCCESS = "GET_TROUSER_BOTTOM_LIST_SUCCESS";
export const GET_TROUSER_BOTTOM_LIST_FAILURE = "GET_TROUSER_BOTTOM_LIST_FAILURE";

export const ADD_TROUSER_BOTTOM_PROGRESS = "ADD_TROUSER_BOTTOM_PROGRESS";
export const ADD_TROUSER_BOTTOM_SUCCESS = "ADD_TROUSER_BOTTOM_SUCCESS";
export const ADD_TROUSER_BOTTOM_FAILURE = "ADD_TROUSER_BOTTOM_FAILURE";

export const EDIT_DELETE_TROUSER_BOTTOM_PROGRESS = "EDIT_DELETE_TROUSER_BOTTOM_PROGRESS";
export const EDIT_DELETE_TROUSER_BOTTOM_SUCCESS = "EDIT_DELETE_TROUSER_BOTTOM_SUCCESS";
export const EDIT_DELETE_TROUSER_BOTTOM_FAILURE = "EDIT_DELETE_TROUSER_BOTTOM_FAILURE";

export const UPLOAD_TROUSER_BOTTOM_IMAGE_PROGRESS = "UPLOAD_TROUSER_BOTTOM_IMAGE_PROGRESS";
export const UPLOAD_TROUSER_BOTTOM_IMAGE_SUCCESS = "UPLOAD_TROUSER_BOTTOM_IMAGE_SUCCESS";
export const UPLOAD_TROUSER_BOTTOM_IMAGE_FAILURE = "UPLOAD_TROUSER_BOTTOM_IMAGE_FAILURE";

// ====================trouser crotch master ======================
export const GET_TROUSER_CROTCH_LIST_PROGRESS = "GET_TROUSER_CROTCH_LIST_PROGRESS";
export const GET_TROUSER_CROTCH_LIST_SUCCESS = "GET_TROUSER_CROTCH_LIST_SUCCESS";
export const GET_TROUSER_CROTCH_LIST_FAILURE = "GET_TROUSER_CROTCH_LIST_FAILURE";

export const ADD_TROUSER_CROTCH_PROGRESS = "ADD_TROUSER_CROTCH_PROGRESS";
export const ADD_TROUSER_CROTCH_SUCCESS = "ADD_TROUSER_CROTCH_SUCCESS";
export const ADD_TROUSER_CROTCH_FAILURE = "ADD_TROUSER_CROTCH_FAILURE";

export const EDIT_DELETE_TROUSER_CROTCH_PROGRESS = "EDIT_DELETE_TROUSER_CROTCH_PROGRESS";
export const EDIT_DELETE_TROUSER_CROTCH_SUCCESS = "EDIT_DELETE_TROUSER_CROTCH_SUCCESS";
export const EDIT_DELETE_TROUSER_CROTCH_FAILURE = "EDIT_DELETE_TROUSER_CROTCH_FAILURE";

export const UPLOAD_TROUSER_CROTCH_IMAGE_PROGRESS = "UPLOAD_TROUSER_CROTCH_IMAGE_PROGRESS";
export const UPLOAD_TROUSER_CROTCH_IMAGE_SUCCESS = "UPLOAD_TROUSER_CROTCH_IMAGE_SUCCESS";
export const UPLOAD_TROUSER_CROTCH_IMAGE_FAILURE = "UPLOAD_TROUSER_CROTCH_IMAGE_FAILURE";


// ====================trouser Pocket master ======================
export const GET_TROUSER_POCKET_LIST_PROGRESS = "GET_TROUSER_POCKET_LIST_PROGRESS";
export const GET_TROUSER_POCKET_LIST_SUCCESS = "GET_TROUSER_POCKET_LIST_SUCCESS";
export const GET_TROUSER_POCKET_LIST_FAILURE = "GET_TROUSER_POCKET_LIST_FAILURE";

export const ADD_TROUSER_POCKET_PROGRESS = "ADD_TROUSER_POCKET_PROGRESS";
export const ADD_TROUSER_POCKET_SUCCESS = "ADD_TROUSER_POCKET_SUCCESS";
export const ADD_TROUSER_POCKET_FAILURE = "ADD_TROUSER_POCKET_FAILURE";

export const EDIT_DELETE_TROUSER_POCKET_PROGRESS = "EDIT_DELETE_TROUSER_POCKET_PROGRESS";
export const EDIT_DELETE_TROUSER_POCKET_SUCCESS = "EDIT_DELETE_TROUSER_POCKET_SUCCESS";
export const EDIT_DELETE_TROUSER_POCKET_FAILURE = "EDIT_DELETE_TROUSER_POCKET_FAILURE";

export const UPLOAD_TROUSER_POCKET_IMAGE_PROGRESS = "UPLOAD_TROUSER_POCKET_IMAGE_PROGRESS";
export const UPLOAD_TROUSER_POCKET_IMAGE_SUCCESS = "UPLOAD_TROUSER_POCKET_IMAGE_SUCCESS";
export const UPLOAD_TROUSER_POCKET_IMAGE_FAILURE = "UPLOAD_TROUSER_POCKET_IMAGE_FAILURE";

// ====================Fabric Masters ======================
export const GET_FABRICS_LIST_PROGRESS = "GET_FABRICS_LIST_PROGRESS";
export const GET_FABRICS_LIST_SUCCESS = "GET_FABRICS_LIST_SUCCESS";
export const GET_FABRICS_LIST_FAILURE = "GET_FABRICS_LIST_FAILURE";

export const ADD_FABRICS_PROGRESS = "ADD_FABRICS_PROGRESS";
export const ADD_FABRICS_SUCCESS = "ADD_FABRICS_SUCCESS";
export const ADD_FABRICS_FAILURE = "ADD_FABRICS_FAILURE";

export const EDIT_DELETE_FABRICS_PROGRESS = "EDIT_DELETE_FABRICS_PROGRESS";
export const EDIT_DELETE_FABRICS_SUCCESS = "EDIT_DELETE_FABRICS_SUCCESS";
export const EDIT_DELETE_FABRICS_FAILURE = "EDIT_DELETE_FABRICS_FAILURE";

// ==================== manufracturers master ======================
export const GET_MANUFRACTURERS_LIST_PROGRESS = "GET_MANUFRACTURERS_LIST_PROGRESS";
export const GET_MANUFRACTURERS_LIST_SUCCESS = "GET_MANUFRACTURERS_LIST_SUCCESS";
export const GET_MANUFRACTURERS_LIST_FAILURE = "GET_MANUFRACTURERS_LIST_FAILURE";

export const ADD_MANUFRACTURERS_PROGRESS = "ADD_MANUFRACTURERS_PROGRESS";
export const ADD_MANUFRACTURERS_SUCCESS = "ADD_MANUFRACTURERS_SUCCESS";
export const ADD_MANUFRACTURERS_FAILURE = "ADD_MANUFRACTURERS_FAILURE";

export const EDIT_DELETE_MANUFRACTURERS_PROGRESS = "EDIT_DELETE_MANUFRACTURERS_PROGRESS";
export const EDIT_DELETE_MANUFRACTURERS_SUCCESS = "EDIT_DELETE_MANUFRACTURERS_SUCCESS";
export const EDIT_DELETE_MANUFRACTURERS_FAILURE = "EDIT_DELETE_MANUFRACTURERS_FAILURE";

// ====================stitching censters ======================
export const GET_STITCHING_CENTERS_LIST_PROGRESS = "GET_STITCHING_CENTERS_LIST_PROGRESS";
export const GET_STITCHING_CENTERS_LIST_SUCCESS = "GET_STITCHING_CENTERS_LIST_SUCCESS";
export const GET_STITCHING_CENTERS_LIST_FAILURE = "GET_STITCHING_CENTERS_LIST_FAILURE";

export const ADD_STITCHING_CENTERS_PROGRESS = "ADD_STITCHING_CENTERS_PROGRESS";
export const ADD_STITCHING_CENTERS_SUCCESS = "ADD_STITCHING_CENTERS_SUCCESS";
export const ADD_STITCHING_CENTERS_FAILURE = "ADD_STITCHING_CENTERS_FAILURE";

export const EDIT_DELETE_STITCHING_CENTERS_PROGRESS = "EDIT_DELETE_STITCHING_CENTERS_PROGRESS";
export const EDIT_DELETE_STITCHING_CENTERS_SUCCESS = "EDIT_DELETE_STITCHING_CENTERS_SUCCESS";
export const EDIT_DELETE_STITCHING_CENTERS_FAILURE = "EDIT_DELETE_STITCHING_CENTERS_FAILURE";

// ==================== tailor shops ======================
export const GET_TAILOR_SHOPS_LIST_PROGRESS = "GET_TAILOR_SHOPS_LIST_PROGRESS";
export const GET_TAILOR_SHOPS_LIST_SUCCESS = "GET_TAILOR_SHOPS_LIST_SUCCESS";
export const GET_TAILOR_SHOPS_LIST_FAILURE = "GET_TAILOR_SHOPS_LIST_FAILURE";

export const ADD_TAILOR_SHOPS_PROGRESS = "ADD_TAILOR_SHOPS_PROGRESS";
export const ADD_TAILOR_SHOPS_SUCCESS = "ADD_TAILOR_SHOPS_SUCCESS";
export const ADD_TAILOR_SHOPS_FAILURE = "ADD_TAILOR_SHOPS_FAILURE";

export const EDIT_DELETE_TAILOR_SHOPS_PROGRESS = "EDIT_DELETE_TAILOR_SHOPS_PROGRESS";
export const EDIT_DELETE_TAILOR_SHOPS_SUCCESS = "EDIT_DELETE_TAILOR_SHOPS_SUCCESS";
export const EDIT_DELETE_TAILOR_SHOPS_FAILURE = "EDIT_DELETE_TAILOR_SHOPS_FAILURE";

////////////////////////////////////////////////////////////////////////////////////////////////
// ====================Waist Coat Bottom Type master ======================

export const GET_WAIST_COAT_BOTTOM_TYPE_LIST_PROGRESS = "GET_WAIST_COAT_BOTTOM_TYPE_LIST_PROGRESS";
export const GET_WAIST_COAT_BOTTOM_TYPE_LIST_SUCCESS = "GET_WAIST_COAT_BOTTOM_TYPE_LIST_SUCCESS";
export const GET_WAIST_COAT_BOTTOM_TYPE_LIST_FAILURE = "GET_WAIST_COAT_BOTTOM_TYPE_LIST_FAILURE";

export const ADD_WAIST_COAT_BOTTOM_TYPE_PROGRESS = "ADD_WAIST_COAT_BOTTOM_TYPE_PROGRESS";
export const ADD_WAIST_COAT_BOTTOM_TYPE_SUCCESS = "ADD_WAIST_COAT_BOTTOM_TYPE_SUCCESS";
export const ADD_WAIST_COAT_BOTTOM_TYPE_FAILURE = "ADD_WAIST_COAT_BOTTOM_TYPE_FAILURE";

export const EDIT_DELETE_WAIST_COAT_BOTTOM_TYPE_PROGRESS = "EDIT_DELETE_WAIST_COAT_BOTTOM_TYPE_PROGRESS";
export const EDIT_DELETE_WAIST_COAT_BOTTOM_TYPE_SUCCESS = "EDIT_DELETE_WAIST_COAT_BOTTOM_TYPE_SUCCESS";
export const EDIT_DELETE_WAIST_COAT_BOTTOM_TYPE_FAILURE = "EDIT_DELETE_WAIST_COAT_BOTTOM_TYPE_FAILURE";

export const UPLOAD_WAIST_COAT_BOTTOM_TYPE_IMAGE_PROGRESS = "UPLOAD_WAIST_COAT_BOTTOM_TYPE_IMAGE_PROGRESS";
export const UPLOAD_WAIST_COAT_BOTTOM_TYPE_IMAGE_SUCCESS = "UPLOAD_WAIST_COAT_BOTTOM_TYPE_IMAGE_SUCCESS ";
export const UPLOAD_WAIST_COAT_BOTTOM_TYPE_IMAGE_FAILURE = "UPLOAD_WAIST_COAT_BOTTOM_TYPE_IMAGE_FAILURE";

// ====================Waist Coat Type master ======================

export const GET_WAIST_COAT_TYPE_LIST_PROGRESS = "GET_WAIST_COAT_TYPE_LIST_PROGRESS";
export const GET_WAIST_COAT_TYPE_LIST_SUCCESS = "GET_WAIST_COAT_TYPE_LIST_SUCCESS";
export const GET_WAIST_COAT_TYPE_LIST_FAILURE = "GET_WAIST_COAT_TYPE_LIST_FAILURE";

export const ADD_WAIST_COAT_TYPE_PROGRESS = "ADD_WAIST_COAT_TYPE_PROGRESS";
export const ADD_WAIST_COAT_TYPE_SUCCESS = "ADD_WAIST_COAT_TYPE_SUCCESS";
export const ADD_WAIST_COAT_TYPE_FAILURE = "ADD_WAIST_COAT_TYPE_FAILURE";

export const EDIT_DELETE_WAIST_COAT_TYPE_PROGRESS = "EDIT_DELETE_WAIST_COAT_TYPE_PROGRESS";
export const EDIT_DELETE_WAIST_COAT_TYPE_SUCCESS = "EDIT_DELETE_WAIST_COAT_TYPE_SUCCESS";
export const EDIT_DELETE_WAIST_COAT_TYPE_FAILURE = "EDIT_DELETE_WAIST_COAT_TYPE_FAILURE";

export const UPLOAD_WAIST_COAT_TYPE_IMAGE_PROGRESS = "UPLOAD_WAIST_COAT_TYPE_IMAGE_PROGRESS";
export const UPLOAD_WAIST_COAT_TYPE_IMAGE_SUCCESS = "UPLOAD_WAIST_COAT_TYPE_IMAGE_SUCCESS";
export const UPLOAD_WAIST_COAT_TYPE_IMAGE_FAILURE = "UPLOAD_WAIST_COAT_TYPE_IMAGE_FAILURE";

// ==================== Waist Coat Neck master ======================

export const GET_WAIST_COAT_NECK_LIST_PROGRESS = "GET_WAIST_COAT_NECK_LIST_PROGRESS";
export const GET_WAIST_COAT_NECK_LIST_SUCCESS = "GET_WAIST_COAT_NECK_LIST_SUCCESS";
export const GET_WAIST_COAT_NECK_LIST_FAILURE = "GET_WAIST_COAT_NECK_LIST_FAILURE";

export const ADD_WAIST_COAT_NECK_PROGRESS = "ADD_WAIST_COAT_NECK_PROGRESS";
export const ADD_WAIST_COAT_NECK_SUCCESS = "ADD_WAIST_COAT_NECK_SUCCESS";
export const ADD_WAIST_COAT_NECK_FAILURE = "ADD_WAIST_COAT_NECK_FAILURE";

export const EDIT_DELETE_WAIST_COAT_NECK_PROGRESS = "EDIT_DELETE_WAIST_COAT_NECK_PROGRESS";
export const EDIT_DELETE_WAIST_COAT_NECK_SUCCESS = "EDIT_DELETE_WAIST_COAT_NECK_SUCCESS";
export const EDIT_DELETE_WAIST_COAT_NECK_FAILURE = "EDIT_DELETE_WAIST_COAT_NECK_FAILURE";

export const UPLOAD_WAIST_COAT_NECK_IMAGE_PROGRESS = "UPLOAD_WAIST_COAT_NECK_IMAGE_PROGRESS";
export const UPLOAD_WAIST_COAT_NECK_IMAGE_SUCCESS = "UPLOAD_WAIST_COAT_NECK_IMAGE_SUCCESS";
export const UPLOAD_WAIST_COAT_NECK_IMAGE_FAILURE = "UPLOAD_WAIST_COAT_NECK_IMAGE_FAILURE";

// ==================== Waist Coat Pocket Master ======================

export const GET_WAIST_COAT_POCKET_LIST_PROGRESS = "GET_WAIST_COAT_POCKET_LIST_PROGRESS";
export const GET_WAIST_COAT_POCKET_LIST_SUCCESS = "GET_WAIST_COAT_POCKET_LIST_SUCCESS";
export const GET_WAIST_COAT_POCKET_LIST_FAILURE = "GET_WAIST_COAT_POCKET_LIST_FAILURE";

export const ADD_WAIST_COAT_POCKET_PROGRESS = "ADD_WAIST_COAT_POCKET_PROGRESS";
export const ADD_WAIST_COAT_POCKET_SUCCESS = "ADD_WAIST_COAT_POCKET_SUCCESS";
export const ADD_WAIST_COAT_POCKET_FAILURE = "ADD_WAIST_COAT_POCKET_FAILURE";

export const EDIT_DELETE_WAIST_COAT_POCKET_PROGRESS = "EDIT_DELETE_WAIST_COAT_POCKET_PROGRESS";
export const EDIT_DELETE_WAIST_COAT_POCKET_SUCCESS = "EDIT_DELETE_WAIST_COAT_POCKET_SUCCESS";
export const EDIT_DELETE_WAIST_COAT_POCKET_FAILURE = "EDIT_DELETE_WAIST_COAT_POCKET_FAILURE";

export const UPLOAD_WAIST_COAT_POCKET_IMAGE_PROGRESS = "UPLOAD_WAIST_COAT_POCKET_IMAGE_PROGRESS";
export const UPLOAD_WAIST_COAT_POCKET_IMAGE_SUCCESS = "UPLOAD_WAIST_COAT_POCKET_IMAGE_SUCCESS";
export const UPLOAD_WAIST_COAT_POCKET_IMAGE_FAILURE = "UPLOAD_WAIST_COAT_POCKET_IMAGE_FAILURE";

// ====================Sherwani Collar Design Master======================

export const GET_SHERWANI_COLLAR_DESIGN_LIST_PROGRESS = "GET_SHERWANI_COLLAR_DESIGN_LIST_PROGRESS";
export const GET_SHERWANI_COLLAR_DESIGN_LIST_SUCCESS = "GET_SHERWANI_COLLAR_DESIGN_LIST_SUCCESS";
export const GET_SHERWANI_COLLAR_DESIGN_LIST_FAILURE = "GET_SHERWANI_COLLAR_DESIGN_LIST_FAILURE";

export const ADD_SHERWANI_COLLAR_DESIGN_PROGRESS = "ADD_SHERWANI_COLLAR_DESIGN_PROGRESS";
export const ADD_SHERWANI_COLLAR_DESIGN_SUCCESS = "ADD_SHERWANI_COLLAR_DESIGN_SUCCESS";
export const ADD_SHERWANI_COLLAR_DESIGN_FAILURE = "ADD_SHERWANI_COLLAR_DESIGN_FAILURE";

export const EDIT_DELETE_SHERWANI_COLLAR_DESIGN_PROGRESS = "EDIT_DELETE_SHERWANI_COLLAR_DESIGN_PROGRESS";
export const EDIT_DELETE_SHERWANI_COLLAR_DESIGN_SUCCESS = "EDIT_DELETE_SHERWANI_COLLAR_DESIGN_SUCCESS";
export const EDIT_DELETE_SHERWANI_COLLAR_DESIGN_FAILURE = "EDIT_DELETE_SHERWANI_COLLAR_DESIGN_FAILURE";

export const UPLOAD_SHERWANI_COLLAR_DESIGN_IMAGE_PROGRESS = "UPLOAD_SHERWANI_COLLAR_DESIGN_IMAGE_PROGRESS";
export const UPLOAD_SHERWANI_COLLAR_DESIGN_IMAGE_SUCCESS = "UPLOAD_SHERWANI_COLLAR_DESIGN_IMAGE_SUCCESS";
export const UPLOAD_SHERWANI_COLLAR_DESIGN_IMAGE_FAILURE = "UPLOAD_SHERWANI_COLLAR_DESIGN_IMAGE_FAILURE";

// ====================Sherwani Collar Master======================

export const GET_SHERWANI_COLLAR_LIST_PROGRESS = "GET_SHERWANI_COLLAR_LIST_PROGRESS";
export const GET_SHERWANI_COLLAR_LIST_SUCCESS = "GET_SHERWANI_COLLAR_LIST_SUCCESS";
export const GET_SHERWANI_COLLAR_LIST_FAILURE = "GET_SHERWANI_COLLAR_LIST_FAILURE";

export const ADD_SHERWANI_COLLAR_PROGRESS = "ADD_SHERWANI_COLLAR_PROGRESS";
export const ADD_SHERWANI_COLLAR_SUCCESS = "ADD_SHERWANI_COLLAR_SUCCESS";
export const ADD_SHERWANI_COLLAR_FAILURE = "ADD_SHERWANI_COLLAR_FAILURE";

export const EDIT_DELETE_SHERWANI_COLLAR_PROGRESS = "EDIT_DELETE_SHERWANI_COLLAR_PROGRESS";
export const EDIT_DELETE_SHERWANI_COLLAR_SUCCESS = "EDIT_DELETE_SHERWANI_COLLAR_SUCCESS";
export const EDIT_DELETE_SHERWANI_COLLAR_FAILURE = "EDIT_DELETE_SHERWANI_COLLAR_FAILURE";

export const UPLOAD_SHERWANI_COLLAR_IMAGE_PROGRESS = "UPLOAD_SHERWANI_COLLAR_IMAGE_PROGRESS";
export const UPLOAD_SHERWANI_COLLAR_IMAGE_SUCCESS = "UPLOAD_SHERWANI_COLLAR_IMAGE_SUCCESS";
export const UPLOAD_SHERWANI_COLLAR_IMAGE_FAILURE = "UPLOAD_SHERWANI_COLLAR_IMAGE_FAILURE";

// ====================Sherwani Cuff Design Master======================

export const GET_SHERWANI_CUFF_DESIGN_LIST_PROGRESS = "GET_SHERWANI_CUFF_DESIGN_LIST_PROGRESS";
export const GET_SHERWANI_CUFF_DESIGN_LIST_SUCCESS = "GET_SHERWANI_CUFF_DESIGN_LIST_SUCCESS";
export const GET_SHERWANI_CUFF_DESIGN_LIST_FAILURE = "GET_SHERWANI_CUFF_DESIGN_LIST_FAILURE";

export const ADD_SHERWANI_CUFF_DESIGN_PROGRESS = "ADD_SHERWANI_CUFF_DESIGN_PROGRESS";
export const ADD_SHERWANI_CUFF_DESIGN_SUCCESS = "ADD_SHERWANI_CUFF_DESIGN_SUCCESS";
export const ADD_SHERWANI_CUFF_DESIGN_FAILURE = "ADD_SHERWANI_CUFF_DESIGN_FAILURE";

export const EDIT_DELETE_SHERWANI_CUFF_DESIGN_PROGRESS = "EDIT_DELETE_SHERWANI_CUFF_DESIGN_PROGRESS";
export const EDIT_DELETE_SHERWANI_CUFF_DESIGN_SUCCESS = "EDIT_DELETE_SHERWANI_CUFF_DESIGN_SUCCESS";
export const EDIT_DELETE_SHERWANI_CUFF_DESIGN_FAILURE = "EDIT_DELETE_SHERWANI_CUFF_DESIGN_FAILURE";

export const UPLOAD_SHERWANI_CUFF_DESIGN_IMAGE_PROGRESS = "UPLOAD_SHERWANI_CUFF_DESIGN_IMAGE_PROGRESS";
export const UPLOAD_SHERWANI_CUFF_DESIGN_IMAGE_SUCCESS = "UPLOAD_SHERWANI_CUFF_DESIGN_IMAGE_SUCCESS";
export const UPLOAD_SHERWANI_CUFF_DESIGN_IMAGE_FAILURE = "UPLOAD_SHERWANI_CUFF_DESIGN_IMAGE_FAILURE";

// ====================Sherwani Cuff Master======================

export const GET_SHERWANI_CUFF_LIST_PROGRESS = "GET_SHERWANI_CUFF_LIST_PROGRESS";
export const GET_SHERWANI_CUFF_LIST_SUCCESS = "GET_SHERWANI_CUFF_LIST_SUCCESS";
export const GET_SHERWANI_CUFF_LIST_FAILURE = "GET_SHERWANI_CUFF_LIST_FAILURE";

export const ADD_SHERWANI_CUFF_PROGRESS = "ADD_SHERWANI_CUFF_PROGRESS";
export const ADD_SHERWANI_CUFF_SUCCESS = "ADD_SHERWANI_CUFF_SUCCESS";
export const ADD_SHERWANI_CUFF_FAILURE = "ADD_SHERWANI_CUFF_FAILURE";

export const EDIT_DELETE_SHERWANI_CUFF_PROGRESS = "EDIT_DELETE_SHERWANI_CUFF_PROGRESS";
export const EDIT_DELETE_SHERWANI_CUFF_SUCCESS = "EDIT_DELETE_SHERWANI_CUFF_SUCCESS";
export const EDIT_DELETE_SHERWANI_CUFF_FAILURE = "EDIT_DELETE_SHERWANI_CUFF_FAILURE";

export const UPLOAD_SHERWANI_CUFF_IMAGE_PROGRESS = "UPLOAD_SHERWANI_CUFF_IMAGE_PROGRESS";
export const UPLOAD_SHERWANI_CUFF_IMAGE_SUCCESS = "UPLOAD_SHERWANI_CUFF_IMAGE_SUCCESS";
export const UPLOAD_SHERWANI_CUFF_IMAGE_FAILURE = "UPLOAD_SHERWANI_CUFF_IMAGE_FAILURE";

// ====================Sherwani Front Master======================

export const GET_SHERWANI_FRONT_LIST_PROGRESS = "GET_SHERWANI_FRONT_LIST_PROGRESS";
export const GET_SHERWANI_FRONT_LIST_SUCCESS = "GET_SHERWANI_FRONT_LIST_SUCCESS";
export const GET_SHERWANI_FRONT_LIST_FAILURE = "GET_SHERWANI_FRONT_LIST_FAILURE";

export const ADD_SHERWANI_FRONT_PROGRESS = "ADD_SHERWANI_FRONT_PROGRESS";
export const ADD_SHERWANI_FRONT_SUCCESS = "ADD_SHERWANI_FRONT_SUCCESS";
export const ADD_SHERWANI_FRONT_FAILURE = "ADD_SHERWANI_FRONT_FAILURE";

export const EDIT_DELETE_SHERWANI_FRONT_PROGRESS = "EDIT_DELETE_SHERWANI_FRONT_PROGRESS";
export const EDIT_DELETE_SHERWANI_FRONT_SUCCESS = "EDIT_DELETE_SHERWANI_FRONT_SUCCESS";
export const EDIT_DELETE_SHERWANI_FRONT_FAILURE = "EDIT_DELETE_SHERWANI_FRONT_FAILURE";

export const UPLOAD_SHERWANI_FRONT_IMAGE_PROGRESS = "UPLOAD_SHERWANI_FRONT_IMAGE_PROGRESS";
export const UPLOAD_SHERWANI_FRONT_IMAGE_SUCCESS = "UPLOAD_SHERWANI_FRONT_IMAGE_SUCCESS";
export const UPLOAD_SHERWANI_FRONT_IMAGE_FAILURE = "UPLOAD_SHERWANI_FRONT_IMAGE_FAILURE";

// ====================Sherwani Jari Design Master======================

export const GET_SHERWANI_JARI_DESIGN_LIST_PROGRESS = "GET_SHERWANI_JARI_DESIGN_LIST_PROGRESS";
export const GET_SHERWANI_JARI_DESIGN_LIST_SUCCESS = "GET_SHERWANI_JARI_DESIGN_LIST_SUCCESS";
export const GET_SHERWANI_JARI_DESIGN_LIST_FAILURE = "GET_SHERWANI_JARI_DESIGN_LIST_FAILURE";

export const ADD_SHERWANI_JARI_DESIGN_PROGRESS = "ADD_SHERWANI_JARI_DESIGN_PROGRESS";
export const ADD_SHERWANI_JARI_DESIGN_SUCCESS = "ADD_SHERWANI_JARI_DESIGN_SUCCESS";
export const ADD_SHERWANI_JARI_DESIGN_FAILURE = "ADD_SHERWANI_JARI_DESIGN_FAILURE";

export const EDIT_DELETE_SHERWANI_JARI_DESIGN_PROGRESS = "EDIT_DELETE_SHERWANI_JARI_DESIGN_PROGRESS";
export const EDIT_DELETE_SHERWANI_JARI_DESIGN_SUCCESS = "EDIT_DELETE_SHERWANI_JARI_DESIGN_SUCCESS";
export const EDIT_DELETE_SHERWANI_JARI_DESIGN_FAILURE = "EDIT_DELETE_SHERWANI_JARI_DESIGN_FAILURE";

export const UPLOAD_SHERWANI_JARI_DESIGN_IMAGE_PROGRESS = "UPLOAD_SHERWANI_JARI_DESIGN_IMAGE_PROGRESS";
export const UPLOAD_SHERWANI_JARI_DESIGN_IMAGE_SUCCESS = "UPLOAD_SHERWANI_JARI_DESIGN_IMAGE_SUCCESS";
export const UPLOAD_SHERWANI_JARI_DESIGN_IMAGE_FAILURE = "UPLOAD_SHERWANI_JARI_DESIGN_IMAGE_FAILURE";

// ====================Sherwani Pocket Master======================

export const GET_SHERWANI_POCKET_LIST_PROGRESS = "GET_SHERWANI_POCKET_LIST_PROGRESS";
export const GET_SHERWANI_POCKET_LIST_SUCCESS = "GET_SHERWANI_POCKET_LIST_SUCCESS";
export const GET_SHERWANI_POCKET_LIST_FAILURE = "GET_SHERWANI_POCKET_LIST_FAILURE";

export const ADD_SHERWANI_POCKET_PROGRESS = "ADD_SHERWANI_POCKET_PROGRESS";
export const ADD_SHERWANI_POCKET_SUCCESS = "ADD_SHERWANI_POCKET_SUCCESS";
export const ADD_SHERWANI_POCKET_FAILURE = "ADD_SHERWANI_POCKET_FAILURE";

export const EDIT_DELETE_SHERWANI_POCKET_PROGRESS = "EDIT_DELETE_SHERWANI_POCKET_PROGRESS";
export const EDIT_DELETE_SHERWANI_POCKET_SUCCESS = "EDIT_DELETE_SHERWANI_POCKET_SUCCESS";
export const EDIT_DELETE_SHERWANI_POCKET_FAILURE = "EDIT_DELETE_SHERWANI_POCKET_FAILURE";

export const UPLOAD_SHERWANI_POCKET_IMAGE_PROGRESS = "UPLOAD_SHERWANI_POCKET_IMAGE_PROGRESS";
export const UPLOAD_SHERWANI_POCKET_IMAGE_SUCCESS = "UPLOAD_SHERWANI_POCKET_IMAGE_SUCCESS";
export const UPLOAD_SHERWANI_POCKET_IMAGE_FAILURE = "UPLOAD_SHERWANI_POCKET_IMAGE_FAILURE";

// ====================Sherwani Side Cut Master======================

export const GET_SHERWANI_SIDE_CUT_LIST_PROGRESS = "GET_SHERWANI_SIDE_CUT_LIST_PROGRESS";
export const GET_SHERWANI_SIDE_CUT_LIST_SUCCESS = "GET_SHERWANI_SIDE_CUT_LIST_SUCCESS";
export const GET_SHERWANI_SIDE_CUT_LIST_FAILURE = "GET_SHERWANI_SIDE_CUT_LIST_FAILURE";

export const ADD_SHERWANI_SIDE_CUT_PROGRESS = "ADD_SHERWANI_SIDE_CUT_PROGRESS";
export const ADD_SHERWANI_SIDE_CUT_SUCCESS = "ADD_SHERWANI_SIDE_CUT_SUCCESS";
export const ADD_SHERWANI_SIDE_CUT_FAILURE = "ADD_SHERWANI_SIDE_CUT_FAILURE";

export const EDIT_DELETE_SHERWANI_SIDE_CUT_PROGRESS = "EDIT_DELETE_SHERWANI_SIDE_CUT_PROGRESS";
export const EDIT_DELETE_SHERWANI_SIDE_CUT_SUCCESS = "EDIT_DELETE_SHERWANI_SIDE_CUT_SUCCESS";
export const EDIT_DELETE_SHERWANI_SIDE_CUT_FAILURE = "EDIT_DELETE_SHERWANI_SIDE_CUT_FAILURE";

export const UPLOAD_SHERWANI_SIDE_CUT_IMAGE_PROGRESS = "UPLOAD_SHERWANI_SIDE_CUT_IMAGE_PROGRESS";
export const UPLOAD_SHERWANI_SIDE_CUT_IMAGE_SUCCESS = "UPLOAD_SHERWANI_SIDE_CUT_IMAGE_SUCCESS";
export const UPLOAD_SHERWANI_SIDE_CUT_IMAGE_FAILURE = "UPLOAD_SHERWANI_SIDE_CUT_IMAGE_FAILURE";

// ====================Kurta Collar Master======================

export const GET_KURTA_COLLAR_LIST_PROGRESS = "GET_KURTA_COLLAR_LIST_PROGRESS";
export const GET_KURTA_COLLAR_LIST_SUCCESS = "GET_KURTA_COLLAR_LIST_SUCCESS";
export const GET_KURTA_COLLAR_LIST_FAILURE = "GET_KURTA_COLLAR_LIST_FAILURE";

export const ADD_KURTA_COLLAR_PROGRESS = "ADD_KURTA_COLLAR_PROGRESS";
export const ADD_KURTA_COLLAR_SUCCESS = "ADD_KURTA_COLLAR_SUCCESS";
export const ADD_KURTA_COLLAR_FAILURE = "ADD_KURTA_COLLAR_FAILURE";

export const EDIT_DELETE_KURTA_COLLAR_PROGRESS = "EDIT_DELETE_KURTA_COLLAR_PROGRESS";
export const EDIT_DELETE_KURTA_COLLAR_SUCCESS = "EDIT_DELETE_KURTA_COLLAR_SUCCESS";
export const EDIT_DELETE_KURTA_COLLAR_FAILURE = "EDIT_DELETE_KURTA_COLLAR_FAILURE";

export const UPLOAD_KURTA_COLLAR_IMAGE_PROGRESS = "UPLOAD_KURTA_COLLAR_IMAGE_PROGRESS";
export const UPLOAD_KURTA_COLLAR_IMAGE_SUCCESS = "UPLOAD_KURTA_COLLAR_IMAGE_SUCCESS";
export const UPLOAD_KURTA_COLLAR_IMAGE_FAILURE = "UPLOAD_KURTA_COLLAR_IMAGE_FAILURE";

// ====================Kurta Front Master======================

export const GET_KURTA_FRONT_LIST_PROGRESS = "GET_KURTA_FRONT_LIST_PROGRESS";
export const GET_KURTA_FRONT_LIST_SUCCESS = "GET_KURTA_FRONT_LIST_SUCCESS";
export const GET_KURTA_FRONT_LIST_FAILURE = "GET_KURTA_FRONT_LIST_FAILURE";

export const ADD_KURTA_FRONT_PROGRESS = "ADD_KURTA_FRONT_PROGRESS";
export const ADD_KURTA_FRONT_SUCCESS = "ADD_KURTA_FRONT_SUCCESS";
export const ADD_KURTA_FRONT_FAILURE = "ADD_KURTA_FRONT_FAILURE";

export const EDIT_DELETE_KURTA_FRONT_PROGRESS = "EDIT_DELETE_KURTA_FRONT_PROGRESS";
export const EDIT_DELETE_KURTA_FRONT_SUCCESS = "EDIT_DELETE_KURTA_FRONT_SUCCESS";
export const EDIT_DELETE_KURTA_FRONT_FAILURE = "EDIT_DELETE_KURTA_FRONT_FAILURE";

export const UPLOAD_KURTA_FRONT_IMAGE_PROGRESS = "UPLOAD_KURTA_FRONT_IMAGE_PROGRESS";
export const UPLOAD_KURTA_FRONT_IMAGE_SUCCESS = "UPLOAD_KURTA_FRONT_IMAGE_SUCCESS";
export const UPLOAD_KURTA_FRONT_IMAGE_FAILURE = "UPLOAD_KURTA_FRONT_IMAGE_FAILURE";

// ====================Kurta Pocket Master======================

export const GET_KURTA_POCKET_LIST_PROGRESS = "GET_KURTA_POCKET_LIST_PROGRESS";
export const GET_KURTA_POCKET_LIST_SUCCESS = "GET_KURTA_POCKET_LIST_SUCCESS";
export const GET_KURTA_POCKET_LIST_FAILURE = "GET_KURTA_POCKET_LIST_FAILURE";

export const ADD_KURTA_POCKET_PROGRESS = "ADD_KURTA_POCKET_PROGRESS";
export const ADD_KURTA_POCKET_SUCCESS = "ADD_KURTA_POCKET_SUCCESS";
export const ADD_KURTA_POCKET_FAILURE = "ADD_KURTA_POCKET_FAILURE";

export const EDIT_DELETE_KURTA_POCKET_PROGRESS = "EDIT_DELETE_KURTA_POCKET_PROGRESS";
export const EDIT_DELETE_KURTA_POCKET_SUCCESS = "EDIT_DELETE_KURTA_POCKET_SUCCESS";
export const EDIT_DELETE_KURTA_POCKET_FAILURE = "EDIT_DELETE_KURTA_POCKET_FAILURE";

export const UPLOAD_KURTA_POCKET_IMAGE_PROGRESS = "UPLOAD_KURTA_POCKET_IMAGE_PROGRESS";
export const UPLOAD_KURTA_POCKET_IMAGE_SUCCESS = "UPLOAD_KURTA_POCKET_IMAGE_SUCCESS";
export const UPLOAD_KURTA_POCKET_IMAGE_FAILURE = "UPLOAD_KURTA_POCKET_IMAGE_FAILURE";

// ====================Kurta Sleeve Master======================

export const GET_KURTA_SLEEVE_LIST_PROGRESS = "GET_KURTA_SLEEVE_LIST_PROGRESS";
export const GET_KURTA_SLEEVE_LIST_SUCCESS = "GET_KURTA_SLEEVE_LIST_SUCCESS";
export const GET_KURTA_SLEEVE_LIST_FAILURE = "GET_KURTA_SLEEVE_LIST_FAILURE";

export const ADD_KURTA_SLEEVE_PROGRESS = "ADD_KURTA_SLEEVE_PROGRESS";
export const ADD_KURTA_SLEEVE_SUCCESS = "ADD_KURTA_SLEEVE_SUCCESS";
export const ADD_KURTA_SLEEVE_FAILURE = "ADD_KURTA_SLEEVE_FAILURE";

export const EDIT_DELETE_KURTA_SLEEVE_PROGRESS = "EDIT_DELETE_KURTA_SLEEVE_PROGRESS";
export const EDIT_DELETE_KURTA_SLEEVE_SUCCESS = "EDIT_DELETE_KURTA_SLEEVE_SUCCESS";
export const EDIT_DELETE_KURTA_SLEEVE_FAILURE = "EDIT_DELETE_KURTA_SLEEVE_FAILURE";

export const UPLOAD_KURTA_SLEEVE_IMAGE_PROGRESS = "UPLOAD_KURTA_SLEEVE_IMAGE_PROGRESS";
export const UPLOAD_KURTA_SLEEVE_IMAGE_SUCCESS = "UPLOAD_KURTA_SLEEVE_IMAGE_SUCCESS";
export const UPLOAD_KURTA_SLEEVE_IMAGE_FAILURE = "UPLOAD_KURTA_SLEEVE_IMAGE_FAILURE";

// ====================Kurta Style Master======================

export const GET_KURTA_STYLE_LIST_PROGRESS = "GET_KURTA_STYLE_LIST_PROGRESS";
export const GET_KURTA_STYLE_LIST_SUCCESS = "GET_KURTA_STYLE_LIST_SUCCESS";
export const GET_KURTA_STYLE_LIST_FAILURE = "GET_KURTA_STYLE_LIST_FAILURE";

export const ADD_KURTA_STYLE_PROGRESS = "ADD_KURTA_STYLE_PROGRESS";
export const ADD_KURTA_STYLE_SUCCESS = "ADD_KURTA_STYLE_SUCCESS";
export const ADD_KURTA_STYLE_FAILURE = "ADD_KURTA_STYLE_FAILURE";

export const EDIT_DELETE_KURTA_STYLE_PROGRESS = "EDIT_DELETE_KURTA_STYLE_PROGRESS";
export const EDIT_DELETE_KURTA_STYLE_SUCCESS = "EDIT_DELETE_KURTA_STYLE_SUCCESS";
export const EDIT_DELETE_KURTA_STYLE_FAILURE = "EDIT_DELETE_KURTA_STYLE_FAILURE";

export const UPLOAD_KURTA_STYLE_IMAGE_PROGRESS = "UPLOAD_KURTA_STYLE_IMAGE_PROGRESS";
export const UPLOAD_KURTA_STYLE_IMAGE_SUCCESS = "UPLOAD_KURTA_STYLE_IMAGE_SUCCESS";
export const UPLOAD_KURTA_STYLE_IMAGE_FAILURE = "UPLOAD_KURTA_STYLE_IMAGE_FAILURE";

// ====================GRN======================

export const GET_GRN_LIST_PROGRESS = "GET_GRN_LIST_PROGRESS";
export const GET_GRN_LIST_SUCCESS = "GET_GRN_LIST_SUCCESS";
export const GET_GRN_LIST_FAILURE = "GET_GRN_LIST_FAILURE";

export const ADD_GRN_PROGRESS = "ADD_GRN_PROGRESS";
export const ADD_GRN_SUCCESS = "ADD_GRN_SUCCESS";
export const ADD_GRN_FAILURE = "ADD_GRN_FAILURE";

export const EDIT_DELETE_GRN_PROGRESS = "EDIT_DELETE_GRN_PROGRESS";
export const EDIT_DELETE_GRN_SUCCESS = "EDIT_DELETE_GRN_SUCCESS";
export const EDIT_DELETE_GRN_FAILURE = "EDIT_DELETE_GRN_FAILURE";

// ====================Order Issue======================

export const GET_ORDER_ISSUE_LIST_PROGRESS = "GET_ORDER_ISSUE_LIST_PROGRESS";
export const GET_ORDER_ISSUE_LIST_SUCCESS = "GET_ORDER_ISSUE_LIST_SUCCESS";
export const GET_ORDER_ISSUE_LIST_FAILURE = "GET_ORDER_ISSUE_LIST_FAILURE";

export const ADD_ORDER_ISSUE_PROGRESS = "ADD_ORDER_ISSUE_PROGRESS";
export const ADD_ORDER_ISSUE_SUCCESS = "ADD_ORDER_ISSUE_SUCCESS";
export const ADD_ORDER_ISSUE_FAILURE = "ADD_ORDER_ISSUE_FAILURE";

export const EDIT_DELETE_ORDER_ISSUE_PROGRESS = "EDIT_DELETE_ORDER_ISSUE_PROGRESS";
export const EDIT_DELETE_ORDER_ISSUE_SUCCESS = "EDIT_DELETE_ORDER_ISSUE_SUCCESS";
export const EDIT_DELETE_ORDER_ISSUE_FAILURE = "EDIT_DELETE_ORDER_ISSUE_FAILURE";

// ====================Orders======================

export const GET_ORDERS_LIST_PROGRESS = "GET_ORDERS_LIST_PROGRESS";
export const GET_ORDERS_LIST_SUCCESS = "GET_ORDERS_LIST_SUCCESS";
export const GET_ORDERS_LIST_FAILURE = "GET_ORDERS_LIST_FAILURE";

// ====================Item Master======================

export const GET_ITEM_LIST_PROGRESS = "GET_ITEM_LIST_PROGRESS";
export const GET_ITEM_LIST_SUCCESS = "GET_ITEM_LIST_SUCCESS";
export const GET_ITEM_LIST_FAILURE = "GET_ITEM_LIST_FAILURE";

export const ADD_ITEM_PROGRESS = "ADD_ITEM_PROGRESS";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE";

export const EDIT_DELETE_ITEM_PROGRESS = "EDIT_DELETE_ITEM_PROGRESS";
export const EDIT_DELETE_ITEM_SUCCESS = "EDIT_DELETE_ITEM_SUCCESS";
export const EDIT_DELETE_ITEM_FAILURE = "EDIT_DELETE_ITEM_FAILURE";

// ====================Item Grade Master======================

export const GET_ITEM_GRADE_LIST_PROGRESS = "GET_ITEM_GRADE_LIST_PROGRESS";
export const GET_ITEM_GRADE_LIST_SUCCESS = "GET_ITEM_GRADE_LIST_SUCCESS";
export const GET_ITEM_GRADE_LIST_FAILURE = "GET_ITEM_GRADE_LIST_FAILURE";

export const ADD_ITEM_GRADE_PROGRESS = "ADD_ITEM_GRADE_PROGRESS";
export const ADD_ITEM_GRADE_SUCCESS = "ADD_ITEM_GRADE_SUCCESS";
export const ADD_ITEM_GRADE_FAILURE = "ADD_ITEM_GRADE_FAILURE";

export const EDIT_DELETE_ITEM_GRADE_PROGRESS = "EDIT_DELETE_ITEM_GRADE_PROGRESS";
export const EDIT_DELETE_ITEM_GRADE_SUCCESS = "EDIT_DELETE_ITEM_GRADE_SUCCESS";
export const EDIT_DELETE_ITEM_GRADE_FAILURE = "EDIT_DELETE_ITEM_GRADE_FAILURE";

// ====================Item Category Master======================

export const GET_ITEM_CATEGORY_LIST_PROGRESS = "GET_ITEM_CATEGORY_LIST_PROGRESS";
export const GET_ITEM_CATEGORY_LIST_SUCCESS = "GET_ITEM_CATEGORY_LIST_SUCCESS";
export const GET_ITEM_CATEGORY_LIST_FAILURE = "GET_ITEM_CATEGORY_LIST_FAILURE";

// ====================User Addresses======================

export const GET_USER_ADDRESSES_LIST_PROGRESS = "GET_USER_ADDRESSES_LIST_PROGRESS";
export const GET_USER_ADDRESSES_LIST_SUCCESS = "GET_USER_ADDRESSES_LIST_SUCCESS";
export const GET_USER_ADDRESSES_LIST_FAILURE = "GET_USER_ADDRESSES_LIST_FAILURE";

export const ADD_USER_ADDRESSES_PROGRESS = "ADD_USER_ADDRESSES_PROGRESS";
export const ADD_USER_ADDRESSES_SUCCESS = "ADD_USER_ADDRESSES_SUCCESS";
export const ADD_USER_ADDRESSES_FAILURE = "ADD_USER_ADDRESSES_FAILURE";

export const EDIT_DELETE_USER_ADDRESSES_PROGRESS = "EDIT_DELETE_USER_ADDRESSES_PROGRESS";
export const EDIT_DELETE_USER_ADDRESSES_SUCCESS = "EDIT_DELETE_USER_ADDRESSES_SUCCESS";
export const EDIT_DELETE_USER_ADDRESSES_FAILURE = "EDIT_DELETE_USER_ADDRESSES_FAILURE";

// ====================User Measurements UpperBody======================

export const GET_USER_MEASUREMENTS_UPPERBODY_LIST_PROGRESS = "GET_USER_MEASUREMENTS_UPPERBODY_LIST_PROGRESS";
export const GET_USER_MEASUREMENTS_UPPERBODY_LIST_SUCCESS = "GET_USER_MEASUREMENTS_UPPERBODY_LIST_SUCCESS";
export const GET_USER_MEASUREMENTS_UPPERBODY_LIST_FAILURE = "GET_USER_MEASUREMENTS_UPPERBODY_LIST_FAILURE";

export const ADD_USER_MEASUREMENTS_UPPERBODY_PROGRESS = "ADD_USER_MEASUREMENTS_UPPERBODY_PROGRESS";
export const ADD_USER_MEASUREMENTS_UPPERBODY_SUCCESS = "ADD_USER_MEASUREMENTS_UPPERBODY_SUCCESS";
export const ADD_USER_MEASUREMENTS_UPPERBODY_FAILURE = "ADD_USER_MEASUREMENTS_UPPERBODY_FAILURE";

export const EDIT_DELETE_USER_MEASUREMENTS_UPPERBODY_PROGRESS = "EDIT_DELETE_USER_MEASUREMENTS_UPPERBODY_PROGRESS";
export const EDIT_DELETE_USER_MEASUREMENTS_UPPERBODY_SUCCESS = "EDIT_DELETE_USER_MEASUREMENTS_UPPERBODY_SUCCESS";
export const EDIT_DELETE_USER_MEASUREMENTS_UPPERBODY_FAILURE = "EDIT_DELETE_USER_MEASUREMENTS_UPPERBODY_FAILURE";

// ====================User Measurements LowerBody======================

export const GET_USER_MEASUREMENTS_LOWERBODY_LIST_PROGRESS = "GET_USER_MEASUREMENTS_LOWERBODY_LIST_PROGRESS";
export const GET_USER_MEASUREMENTS_LOWERBODY_LIST_SUCCESS = "GET_USER_MEASUREMENTS_LOWERBODY_LIST_SUCCESS";
export const GET_USER_MEASUREMENTS_LOWERBODY_LIST_FAILURE = "GET_USER_MEASUREMENTS_LOWERBODY_LIST_FAILURE";

export const ADD_USER_MEASUREMENTS_LOWERBODY_PROGRESS = "ADD_USER_MEASUREMENTS_LOWERBODY_PROGRESS";
export const ADD_USER_MEASUREMENTS_LOWERBODY_SUCCESS = "ADD_USER_MEASUREMENTS_LOWERBODY_SUCCESS";
export const ADD_USER_MEASUREMENTS_LOWERBODY_FAILURE = "ADD_USER_MEASUREMENTS_LOWERBODY_FAILURE";

export const EDIT_DELETE_USER_MEASUREMENTS_LOWERBODY_PROGRESS = "EDIT_DELETE_USER_MEASUREMENTS_LOWERBODY_PROGRESS";
export const EDIT_DELETE_USER_MEASUREMENTS_LOWERBODY_SUCCESS = "EDIT_DELETE_USER_MEASUREMENTS_LOWERBODY_SUCCESS";
export const EDIT_DELETE_USER_MEASUREMENTS_LOWERBODY_FAILURE = "EDIT_DELETE_USER_MEASUREMENTS_LOWERBODY_FAILURE";

// ====================Standard Measurements UpperBody======================

export const GET_STANDARD_MEASUREMENTS_UPPERBODY_LIST_PROGRESS = "GET_STANDARD_MEASUREMENTS_UPPERBODY_LIST_PROGRESS";
export const GET_STANDARD_MEASUREMENTS_UPPERBODY_LIST_SUCCESS = "GET_STANDARD_MEASUREMENTS_UPPERBODY_LIST_SUCCESS";
export const GET_STANDARD_MEASUREMENTS_UPPERBODY_LIST_FAILURE = "GET_STANDARD_MEASUREMENTS_UPPERBODY_LIST_FAILURE";

export const ADD_STANDARD_MEASUREMENTS_UPPERBODY_PROGRESS = "ADD_STANDARD_MEASUREMENTS_UPPERBODY_PROGRESS";
export const ADD_STANDARD_MEASUREMENTS_UPPERBODY_SUCCESS = "ADD_STANDARD_MEASUREMENTS_UPPERBODY_SUCCESS";
export const ADD_STANDARD_MEASUREMENTS_UPPERBODY_FAILURE = "ADD_STANDARD_MEASUREMENTS_UPPERBODY_FAILURE";

export const EDIT_DELETE_STANDARD_MEASUREMENTS_UPPERBODY_PROGRESS = "EDIT_DELETE_STANDARD_MEASUREMENTS_UPPERBODY_PROGRESS";
export const EDIT_DELETE_STANDARD_MEASUREMENTS_UPPERBODY_SUCCESS = "EDIT_DELETE_STANDARD_MEASUREMENTS_UPPERBODY_SUCCESS";
export const EDIT_DELETE_STANDARD_MEASUREMENTS_UPPERBODY_FAILURE = "EDIT_DELETE_STANDARD_MEASUREMENTS_UPPERBODY_FAILURE";

// ====================Standard Measurements LowerBody======================

export const GET_STANDARD_MEASUREMENTS_LOWERBODY_LIST_PROGRESS = "GET_STANDARD_MEASUREMENTS_LOWERBODY_LIST_PROGRESS";
export const GET_STANDARD_MEASUREMENTS_LOWERBODY_LIST_SUCCESS = "GET_STANDARD_MEASUREMENTS_LOWERBODY_LIST_SUCCESS";
export const GET_STANDARD_MEASUREMENTS_LOWERBODY_LIST_FAILURE = "GET_STANDARD_MEASUREMENTS_LOWERBODY_LIST_FAILURE";

export const ADD_STANDARD_MEASUREMENTS_LOWERBODY_PROGRESS = "ADD_STANDARD_MEASUREMENTS_LOWERBODY_PROGRESS";
export const ADD_STANDARD_MEASUREMENTS_LOWERBODY_SUCCESS = "ADD_STANDARD_MEASUREMENTS_LOWERBODY_SUCCESS";
export const ADD_STANDARD_MEASUREMENTS_LOWERBODY_FAILURE = "ADD_STANDARD_MEASUREMENTS_LOWERBODY_FAILURE";

export const EDIT_DELETE_STANDARD_MEASUREMENTS_LOWERBODY_PROGRESS = "EDIT_DELETE_STANDARD_MEASUREMENTS_LOWERBODY_PROGRESS";
export const EDIT_DELETE_STANDARD_MEASUREMENTS_LOWERBODY_SUCCESS = "EDIT_DELETE_STANDARD_MEASUREMENTS_LOWERBODY_SUCCESS";
export const EDIT_DELETE_STANDARD_MEASUREMENTS_LOWERBODY_FAILURE = "EDIT_DELETE_STANDARD_MEASUREMENTS_LOWERBODY_FAILURE";





